=== dhis2/external-layers/xyz/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Stamen Terrain",
  "description": "",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string"
    },
    "attribution": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "minLength": 1
    },
    "position": {
      "type": "string",
      "enum": ["basemap", "overlay"]
    }
  },
  "required": ["id", "name", "description", "url"],
  "additionalProperties": false
}

=== dhis2/external-layers/xyz/voyager.json
{
  "id": "xyz_voyager",
  "name": "Carto Voyager Raster",
  "description": "A bright, high contrast map designed for data visualization",
  "url": "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{scale}.png",
  "attribution": "<a href=\"http://stamen.com\">Stamen Design</a>, <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a>",
  "position": "basemap"
}
